---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  namespace: nginx
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: nginx
  endpoints:
    - interval: 5s
      path: /metrics
      port: "metrics"
  namespaceSelector:
    matchNames:
      - "nginx"
